import { Navbar } from "@/Components";
import "./globals.css";

import { Footer } from "@/Components/sections";

export const metadata = {
  title: "Modern Website",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=1"],
    apple: ["/apple-touch-icon.png?v=4"],
    shortcut: ["/apple-touch-icon.png"],
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://stijndv.com" />

        <link
          rel="stylesheet"
          href="https://stijndv.com/fonts/Eudoxus-Sans.css"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="text-white bg-gradient-to-r from-[#10112a] min-h-full via-[#1b173b]  to-[#0c1e3c]  ">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
